namespace JdiCodeGenerator.Core.ObjectModel.Abstract
{
    public enum JdiElementTypes
    {
        Element,
        Button,
        CheckBox,
        DatePicker,
        FileInput,
        Image,
        Label,
        Link,
        Text,
        TextArea,
        TextField,
        DropDown,
        MenuItem,
        Tabs,
        TabItem,
        NavBar,
        Form,
        Pagination,
        Pager,
        Progress,
        List,
        ListItem,
        Table
    }
}